export const COUNTRY_PHONE_DATA: Record<string, { code: string; flag: string; pattern: RegExp; maxLength: number; placeholder: string; grouping: number[] }> = {
    "France": { code: "+33", flag: "🇫🇷", pattern: /.*/, maxLength: 10, placeholder: "06 12 34 56 78", grouping: [2, 2, 2, 2, 2] },
    "Belgique": { code: "+32", flag: "🇧🇪", pattern: /.*/, maxLength: 10, placeholder: "0412 34 56 78", grouping: [4, 2, 2, 2] },
    "Suisse": { code: "+41", flag: "🇨🇭", pattern: /.*/, maxLength: 10, placeholder: "079 123 45 67", grouping: [3, 3, 2, 2] },
    "Luxembourg": { code: "+352", flag: "🇱🇺", pattern: /.*/, maxLength: 9, placeholder: "621 123 456", grouping: [3, 3, 3] },
    "Allemagne": { code: "+49", flag: "🇩🇪", pattern: /.*/, maxLength: 11, placeholder: "0151 1234567", grouping: [4, 7] },
    "Espagne": { code: "+34", flag: "🇪🇸", pattern: /.*/, maxLength: 9, placeholder: "612 345 678", grouping: [3, 3, 3] },
    "Italie": { code: "+39", flag: "🇮🇹", pattern: /.*/, maxLength: 10, placeholder: "312 345 6789", grouping: [3, 3, 4] },
    "Portugal": { code: "+351", flag: "🇵🇹", pattern: /.*/, maxLength: 9, placeholder: "912 345 678", grouping: [3, 3, 3] },
    "Royaume-Uni": { code: "+44", flag: "🇬🇧", pattern: /.*/, maxLength: 11, placeholder: "07123 456789", grouping: [5, 6] },
    "Irlande": { code: "+353", flag: "🇮🇪", pattern: /.*/, maxLength: 10, placeholder: "087 123 4567", grouping: [3, 3, 4] },
    "Pays-Bas": { code: "+31", flag: "🇳🇱", pattern: /.*/, maxLength: 10, placeholder: "06 1234 5678", grouping: [2, 4, 4] },
    "Autriche": { code: "+43", flag: "🇦🇹", pattern: /.*/, maxLength: 11, placeholder: "0664 1234567", grouping: [4, 7] },
    "Suède": { code: "+46", flag: "🇸🇪", pattern: /.*/, maxLength: 10, placeholder: "070 123 45 67", grouping: [3, 3, 2, 2] },
    "Norvège": { code: "+47", flag: "🇳🇴", pattern: /.*/, maxLength: 8, placeholder: "412 34 567", grouping: [3, 2, 3] },
    "Danemark": { code: "+45", flag: "🇩🇰", pattern: /.*/, maxLength: 8, placeholder: "12 34 56 78", grouping: [2, 2, 2, 2] },
    "Finlande": { code: "+358", flag: "🇫🇮", pattern: /.*/, maxLength: 10, placeholder: "040 123 4567", grouping: [3, 3, 4] },
    "Brésil": { code: "+55", flag: "🇧🇷", pattern: /.*/, maxLength: 11, placeholder: "11 91234 5678", grouping: [2, 5, 4] },
    "Argentine": { code: "+54", flag: "🇦🇷", pattern: /.*/, maxLength: 10, placeholder: "11 1234 5678", grouping: [2, 4, 4] },
    "Colombie": { code: "+57", flag: "🇨🇴", pattern: /.*/, maxLength: 10, placeholder: "310 123 4567", grouping: [3, 3, 4] },
    "Chili": { code: "+56", flag: "🇨🇱", pattern: /.*/, maxLength: 9, placeholder: "9 1234 5678", grouping: [1, 4, 4] },
    "Pérou": { code: "+51", flag: "🇵🇪", pattern: /.*/, maxLength: 9, placeholder: "912 345 678", grouping: [3, 3, 3] },
    "Équateur": { code: "+593", flag: "🇪🇨", pattern: /.*/, maxLength: 10, placeholder: "09 1234 5678", grouping: [2, 4, 4] },
    "Uruguay": { code: "+598", flag: "🇺🇾", pattern: /.*/, maxLength: 9, placeholder: "099 123 456", grouping: [3, 3, 3] },
    "Paraguay": { code: "+595", flag: "🇵🇾", pattern: /.*/, maxLength: 10, placeholder: "0981 123 456", grouping: [4, 3, 3] },
    "Bolivie": { code: "+591", flag: "🇧🇴", pattern: /.*/, maxLength: 8, placeholder: "7 123 4567", grouping: [1, 3, 4] },
    "Guyana": { code: "+592", flag: "🇬🇾", pattern: /.*/, maxLength: 7, placeholder: "612 3456", grouping: [3, 4] },
    "Suriname": { code: "+597", flag: "🇸🇷", pattern: /.*/, maxLength: 7, placeholder: "812 3456", grouping: [3, 4] },
    "Venezuela": { code: "+58", flag: "🇻🇪", pattern: /.*/, maxLength: 11, placeholder: "0412 123 4567", grouping: [4, 3, 4] }
};

export const COUNTRIES = [
    "France", "Belgique", "Suisse", "Luxembourg", "Allemagne", "Espagne", "Italie", "Portugal",
    "Royaume-Uni", "Irlande", "Pays-Bas", "Autriche", "Suède", "Norvège", "Danemark", "Finlande",
    "Brésil", "Argentine", "Colombie", "Chili", "Pérou", "Équateur", "Uruguay", "Paraguay",
    "Bolivie", "Guyana", "Suriname", "Venezuela"
].sort();

export const COUNTRY_TO_NATIONALITY: Record<string, string> = {
    "France": "Française",
    "Belgique": "Belge",
    "Suisse": "Suisse",
    "Luxembourg": "Luxembourgeoise",
    "Allemagne": "Allemande",
    "Espagne": "Espagnole",
    "Italie": "Italienne",
    "Portugal": "Portugaise",
    "Royaume-Uni": "Britannique",
    "Irlande": "Irlandaise",
    "Pays-Bas": "Néerlandaise",
    "Autriche": "Autrichienne",
    "Suède": "Suédoise",
    "Norvège": "Norvégienne",
    "Danemark": "Danoise",
    "Finlande": "Finlandaise",
    "Brésil": "Brésilienne",
    "Argentine": "Argentine",
    "Colombie": "Colombienne",
    "Chili": "Chilienne",
    "Pérou": "Péruvienne",
    "Équateur": "Équatorienne",
    "Uruguay": "Uruguayenne",
    "Paraguay": "Paraguayenne",
    "Bolivie": "Bolivienne",
    "Guyana": "Guyanienne",
    "Suriname": "Surinamaise",
    "Venezuela": "Vénézuélienne"
};
